---
title: "prostate"
author: "Nathan Kurtz-Enko"
date: "3/26/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(stringr) ## for string manipulation
library(glmnet)


```


```{r}
prostate <- read_csv("~/ADM/class/Prostate.csv")
```


```{r}
sampleSize <- nrow(prostate)
#num predictors
numPreds <- length(names(prostate))-1

#predictor indices
allPreds <- 1:(numPreds)

#currently used predictors
currPreds <- c()

#available or non-used predictors
availPreds <- setdiff(allPreds,currPreds)

#max num predictors
maxPreds <- numPreds

#min mse's computed during ensuing loops
maxMSE <- numeric(maxPreds)

minMSE <- numeric(maxPreds)
```

```{r}
mseBoot <- function(data.df,M=50){
    mse <- rep(0,M)
    for(m in 1:M){
        bootSamp <- sample(1:sampleSize,sampleSize,rep=T)
        outOfBag <- setdiff(1:sampleSize,bootSamp)
        train.df <- data.df[bootSamp,]
        test.df <-   data.df[outOfBag,]
        mod <- lm(lpsa~.,data=train.df)
        vals <- predict(mod,newdata=test.df)
        mse[m] <- with(test.df,mean((lpsa-vals)^2))
    }
    mean(mse)
}



```

```{r}
stuff <- tibble(Preds = 1:(numPreds-1), mse = 1:(numPreds-1), num = 1:(numPreds-1))

tot <- maxPreds
while(tot>0){
  allMSE <- numeric(length(availPreds))
  ctr <- 1
  for(id in availPreds){
    data <- prostate[,c(availPreds[-id], numPreds+1)]
    mse <- mseBoot(data, 30)
    allMSE[ctr] <- mse
    ctr <- ctr+1
  }
  id <- which.min(allMSE)
  id
  worstPred <- availPreds[id]
  worstPred
  bestPreds <- availPreds[-id]
  bestPreds
  bestMSE <- min(allMSE)
  stuff[tot-1,1] = paste(bestPreds, collapse = ",")
  stuff[tot-1,2] = bestMSE
  currPreds <- c(currPreds,worstPred)
  currPreds
  tot <- tot-1
  #maxMSE[tot] <- worstMSE
  availPreds <- setdiff(allPreds,currPreds)
  availPreds
  #availPreds
  ## Print stuff out for debugging and attention-grabbing
  #print(sprintf("Predictor removed: %s  MSE Value: %s",worstPred,worstMSE))
  #print(currPreds)
}

stuff <- add_row(stuff, Preds = paste(allPreds, collapse = ","), mse = mseBoot(prostate, 30), num = numPreds)
```


```{r}
sampleSize <- nrow(prostate)
#num predictors
numPreds <- length(names(prostate))-1

#predictor indices
allPreds <- 1:(numPreds)

#currently used predictors
currPreds <- c()

#available or non-used predictors
availPreds <- setdiff(allPreds,currPreds)

#max num predictors
maxPreds <- numPreds

#min mse's computed during ensuing loops
minMSE <- numeric(maxPreds)
```

```{r}
stuff2 <- tibble(preds = allPreds, mse = allPreds, num = allPreds)
tot <- 0
while( tot < maxPreds){
    ##add predictor which decreases MSE (as determined by CV or
    ##Bootstrapping)
    ## The MSEs computed as we add each of the available predictors
    allMSE <- numeric(length(availPreds))
    ctr<-1
    for(id in availPreds){
        data.df <- prostate[,c(currPreds,id,numPreds+1)]
        mse <- mseBoot(data.df)
        ##mse <- mseBoot(data.df,30)
        allMSE[ctr] <- mse
        ctr<-ctr+1
    }
    ##Find the min
    id <- which.min(allMSE)
    id
    ##get the best predictor and MSW
    bestPred <- availPreds[id]
    bestPred
    bestMSE <- min(allMSE)
    bestMSE
    ##Add these into the collection
    currPreds <- c(currPreds,bestPred)
    currPreds
    tot <-tot+1
    #minMSE[tot] <- bestMSE
    availPreds <- setdiff(allPreds,currPreds)
    #availPreds
    stuff2[tot, 1] = paste(currPreds, collapse = ",")
    stuff2[tot, 2] = bestMSE
    ## Print stuff out for debugging and attention-grabbing
    #print(sprintf("Predictor Added: %s  MSE Value: %s",bestPred,bestMSE))
    #print(currPreds)
}

```

```{r}
stuff
stuff2
```

```{r}
ggplot()+
  geom_point(data = stuff, aes(x = num, y = mse), color = "red")+
  geom_line(data = stuff, aes(x = num, y = mse), color = "red")+
  geom_point(data = stuff2, aes(x = num, y = mse), color = "blue")+
  geom_line(data = stuff2, aes(x = num, y = mse), color = "blue")+
  ggtitle("Forward (blue) vs Backward (red) Selection ")+
  xlab("Number of Predictors Used")+
  ylab("MSE")
```


In this graphic we can see which values for the number of predictors used yield the lowest MSE. The associated predictors are the best to use in order to develop the best model. The best set of predictors for backward selection doesn't seem to be always the same as the set of predictors for forward selection, although there is often some overlap in what they are.

```{r}
backset <- stuff %>%
  filter(mse == min(stuff$mse))
backset <- backset$Preds
forwset <- stuff2 %>%
  filter(mse == min(stuff2$mse))
forwset <- forwset$preds

cat(paste0(str_c("The indices for the predictors used in Forward selection are: ", forwset,". \n", "While the indices for the predictors used in Backward selection are: ", backset, ".")))
```

