---
title: "lasso comparison"
author: "Nathan Kurtz-Enko"
date: "3/26/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(stringr) ## for string manipulation
library(glmnet)


```

```{r}
prostate <- read_csv("~/ADM/class/Prostate.csv")
```

```{r}
N <- nrow(prostate)
sampleSize <- sample(1:N, N/2, replace = FALSE)

train <- prostate[sampleSize,]
test <- prostate[-sampleSize,]
```


```{r}
numCol <- ncol(prostate)
numPreds <- numCol-1

x.train <- as.matrix(train[, 1:numPreds])
y.train <- as.matrix(train[, numPreds+1])

x.test <- as.matrix(test[, 1:numPreds])
y.test <- as.matrix(test[, 1:numPreds])
```


```{r}
numLambda<-10 
lambda.grid<-10^seq(-2,2,length=numLambda)
cv.lasso <-
    cv.glmnet(x.train,y.train, alpha=1,intercept=F,lambda=lambda.grid)
lambda.opt <- cv.lasso$lambda.min
```

```{r}
mod.lasso <-
    glmnet(x.train,y.train, alpha=1,intercept=F,lambda=lambda.opt)

pred.lasso.test <- predict(mod.lasso,newx=x.test, type = "response")
mse.lasso.test <- mean((test$lpsa-pred.lasso.test)^2)

mse.lasso.test
```

```{r}
coef.lasso<- coef(mod.lasso)[-1,1] ##drop intercept
coefs.df <- as.data.frame(as.matrix(coef.lasso))[,1]
indices <- paste(which(coefs.df != 0), collapse = ",")

```

```{r}
sampleSize <- nrow(prostate)
#num predictors
numPreds <- length(names(prostate))-1

#predictor indices
allPreds <- 1:(numPreds)

#currently used predictors
currPreds <- c()

#available or non-used predictors
availPreds <- setdiff(allPreds,currPreds)

#max num predictors
maxPreds <- numPreds

#min mse's computed during ensuing loops
maxMSE <- numeric(maxPreds)

minMSE <- numeric(maxPreds)
```

```{r}
mseBoot <- function(data.df,M=50){
    mse <- rep(0,M)
    for(m in 1:M){
        bootSamp <- sample(1:sampleSize,sampleSize,rep=T)
        outOfBag <- setdiff(1:sampleSize,bootSamp)
        train.df <- data.df[bootSamp,]
        test.df <-   data.df[outOfBag,]
        mod <- lm(lpsa~.,data=train.df)
        vals <- predict(mod,newdata=test.df)
        mse[m] <- with(test.df,mean((lpsa-vals)^2))
    }
    mean(mse)
}



```

```{r}
stuff <- tibble(Preds = 1:(numPreds-1), mse = 1:(numPreds-1), num = 1:(numPreds-1))

tot <- maxPreds
while(tot>0){
  allMSE <- numeric(length(availPreds))
  ctr <- 1
  for(id in availPreds){
    data <- prostate[,c(availPreds[-id], numPreds+1)]
    mse <- mseBoot(data, 30)
    allMSE[ctr] <- mse
    ctr <- ctr+1
  }
  id <- which.min(allMSE)
  id
  worstPred <- availPreds[id]
  worstPred
  bestPreds <- availPreds[-id]
  bestPreds
  bestMSE <- min(allMSE)
  stuff[tot-1,1] = paste(bestPreds, collapse = ",")
  stuff[tot-1,2] = bestMSE
  currPreds <- c(currPreds,worstPred)
  currPreds
  tot <- tot-1
  #maxMSE[tot] <- worstMSE
  availPreds <- setdiff(allPreds,currPreds)
  availPreds
  #availPreds
  ## Print stuff out for debugging and attention-grabbing
  #print(sprintf("Predictor removed: %s  MSE Value: %s",worstPred,worstMSE))
  #print(currPreds)
}

stuff <- add_row(stuff, Preds = paste(allPreds, collapse = ","), mse = mseBoot(prostate, 30), num = numPreds)
```


```{r}
sampleSize <- nrow(prostate)
#num predictors
numPreds <- length(names(prostate))-1

#predictor indices
allPreds <- 1:(numPreds)

#currently used predictors
currPreds <- c()

#available or non-used predictors
availPreds <- setdiff(allPreds,currPreds)

#max num predictors
maxPreds <- numPreds

#min mse's computed during ensuing loops
minMSE <- numeric(maxPreds)
```

```{r}
stuff2 <- tibble(preds = allPreds, mse = allPreds, num = allPreds)
tot <- 0
while( tot < maxPreds){
    ##add predictor which decreases MSE (as determined by CV or
    ##Bootstrapping)
    ## The MSEs computed as we add each of the available predictors
    allMSE <- numeric(length(availPreds))
    ctr<-1
    for(id in availPreds){
        data.df <- prostate[,c(currPreds,id,numPreds+1)]
        mse <- mseBoot(data.df)
        ##mse <- mseBoot(data.df,30)
        allMSE[ctr] <- mse
        ctr<-ctr+1
    }
    ##Find the min
    id <- which.min(allMSE)
    id
    ##get the best predictor and MSW
    bestPred <- availPreds[id]
    bestPred
    bestMSE <- min(allMSE)
    bestMSE
    ##Add these into the collection
    currPreds <- c(currPreds,bestPred)
    currPreds
    tot <-tot+1
    #minMSE[tot] <- bestMSE
    availPreds <- setdiff(allPreds,currPreds)
    #availPreds
    stuff2[tot, 1] = paste(currPreds, collapse = ",")
    stuff2[tot, 2] = bestMSE
    ## Print stuff out for debugging and attention-grabbing
    #print(sprintf("Predictor Added: %s  MSE Value: %s",bestPred,bestMSE))
    #print(currPreds)
}

```


```{r}
backset <- stuff %>%
  filter(mse == min(stuff$mse))
backmse <- backset$mse
backset <- backset$Preds
forwset <- stuff2 %>%
  filter(mse == min(stuff2$mse))
forwmse <- forwset$mse
forwset <- forwset$preds

cat(paste0(str_c("The indices for the predictors used in Forward selection are: ", forwset, ". \n", "While the indices for the predictors used in Backward selection are: ", backset, ". \n", "And lastly, the predictors used by lasso are: ", indices)))

cat(paste0(str_c("The MSE for forward selection predictors is: ", forwmse, ". \n", "While the MSE for backward selection is: ", backmse, ". \n", "And lastly, the mse for lasso is: ", mse.lasso.test)))
```

